
# HAI702 - TP 1 - Parcours ALGO - Algèbre linéaire et graphes

Les graphes non-orientés sont un concept fondamental en combinatoire. On peut représenter un graphe sous la forme matricielle via sa matrice d'adjacence ou via sa matrice d'incidence (entre autres). Dans ce TP, nous allons explorer ce pont entre l'algèbre et la combinatoire en exprimant des propriétés combinatoires des graphes à partir d'outils d'algèbre linéaire. 

<div id="ch:graphes"></div>



**Concepts abordés.**

* Manipulation de tableau de type `array` du package `numpy`

* implémentation de quelques fonctions élémentaires de calcul matriciel

* Matrice d'adjacence d'un graphe non-orienté

* Recherche de chemins et de triangles dans un graphe

* Matrice d'incidence d'un graphe non-orienté

* Analyse du rang des matrices d'incidence






<!-- --- begin exercise --- -->

# Exercice 1: Les matrices avec Numpy

Dans ce TP, nous aurons besoin de la librairie `numpy` :


In [7]:
import numpy as np # ne pas modifier cette ligne. 
# on importe la librairie numpy. Pour appeler une fonction de cette librairie, il faut la préceder par `np.`

Une matrice est un objet de type `array` du package `numpy`. Par exemple, pour définir la matrice $M$ suivante

\begin{pmatrix}
1 & 2 & 3 & 0 & -1\\
0 & -2 & 6 & 0 & 5\\
-1 & 6 & 0 & -2 & 4\\
\end{pmatrix}

on écrira



In [6]:
M = np.array([[1,2,3,0,-1],
              [0,-2,6,0,5],
              [-1,6,0,-2,4]])
print(M)

[[ 1  2  3  0 -1]
 [ 0 -2  6  0  5]
 [-1  6  0 -2  4]]


L'argument de la function `array` est ici de type `list`. Pour créer une matrice contenant des entiers, l'argument doit être une liste de listes d'entiers. Pour plus de détails concernant la fonction `array`, on pourra consulter la documentation <a href="https://numpy.org/doc/stable/reference/generated/numpy.array.html">ici</a>. On accède par exemple au dimensions de la matrice grace à l'attribut `shape`.

In [4]:
M.shape

(3, 5)

Pour accéder à l'élément situé sur la $i$-ème ligne et à la colonne $j$-ème colonne, on écrit `M[i-1][j-1]`. On peut également modifier la valeur de cet élément. Par exemple, 

In [11]:
print(M[1][4])
M[1][4]=-42
print(M)

5
[[  1   2   3   0  -1]
 [  0  -2   6   0 -42]
 [ -1   6   0  -2   4]]


On peut créer une matrice de dimension $n\times m$ dont tous les éléments sont $0$ en appelant la fonction `np.zeros((n,m))` :

In [12]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


**Attention :** Pour copier une matrice (ou plus généralement un objet de type `array`) il faut utiliser la méthode `copy()`. Consider par exemple les codes suivants. 

In [15]:
# Exemple d'une erreur classique
a = np.array([5,3,0,1]) # on crée un tableau a
b = a # on pense faire une copie b de a
b[1] = 145 # on modifie b
print(a) # on peut observer dans la sortie que le tableau a a été également modifié. 
# A la ligne 3, on a simplement donné un autre étiquette au tableau, 
# mais le contenu du tableau n'a pas été copié

[  5 145   0   1]


In [16]:
a = np.array([5,3,0,1]) # on crée un tableau a
b = a.copy() # on fait une (vraie) copie de a 
b[1] = 145 # on modifie b
print(a) # on peut observer que cette fois le tableau a n'a pas été modifié. 

[5 3 0 1]


## Fonctions de bases sur les matrices

Dans cette partie, on ré-implémente quelques fonctions de la librairie Numpy. 

**a)** Ecrire une fonction `matrice_id` qui prend un entier $n$ en paramètre et qui renvoie la matrice identité de taille $n\times n$.

La fonction `matrice_id` s'appelle `eye` dans Numpy. Voir la <a href="https://numpy.org/doc/stable/reference/generated/numpy.eye.html">documentation</a>.

**b)** Ecrire une fonction `transpose` qui prend en entrée une matrice $M$ et renvoie sa transposée $~^tM$.

La fonction `transpose` s'appelle également `transpose` dans Numpy. Voir la <a href="https://numpy.org/doc/stable/reference/generated/numpy.transpose.html">documentation</a>.

**c)** Ecrire une fonction `produit` qui prend en entrée deux matrices $A$ et $B$ et renvoie leur produit. 

La fonction `produit` s'appelle `dot` dans Numpy. Voir la <a href="https://numpy.org/doc/stable/reference/generated/numpy.dot.html">documentation</a>.


**d)** Ecrire une fonction `trace` qui prend en entrée une matrice et renvoie sa trace. 

La fonction `trace` s'appelle également `trace` dans Numpy. Voir la <a href="https://numpy.org/doc/stable/reference/generated/numpy.trace.html">documentation</a>.

Pour connaître davantage de possibilités de Numpy (notamment les méthodes de *slicing* qui sont très pratiques pour la manipulation des tableaux), consulter la <a href="https://numpy.org/doc/stable/user/quickstart.html#quickstart-indexing-slicing-and-iterating">documentation</a>. 


## Pivot de Gauss et rang

Dans cette partie nous allons implémenter l'algorithme du pivot de Gauss. Pour un rappel sur cette méthode, consulter le cours ou <a href="https://en.wikipedia.org/wiki/Gaussian_elimination">wikipédia</a>.
<!--
**a)** Ecrire une fonction `echange(M,i)` qui prend en entrée un matrice $M$, et un entier $i$ et échange la 1ère ligne de $M$ avec sa ligne d'indice $i$. 
**b)** Ecrire une fonction `soustrait(M,i,x)` qui à la ligne d'indice $i$ d'une mtrice $M$, soustrait $x$ fois sa première ligne. 
**c)** Ecrire une fonction `reduit`
**a)** Ecrire une fonction `determinant(M)` qui renvoie la valeur du déterminant d'une matrice $M$ carrée, en utilisant la méthode du Pivot de Gauss.  
-->


**e)** écrire une fonction `rang(M)` qui à l'aide de la méthode du pivot de Gauss, calcule le rang de la matrice $M$. 

**Precision :** On suppose ici que les éléments de la matrice sont de "petits" entiers. Les manipulations de "gros" entiers avec Python peut poser des problèmes inattendus, notamment avec l'utilisation de la division. Par exemple, observer le code suivant.

In [16]:
a = np.array([156436754289756437598670967586])
b = 1/a[0]
c = b*a[0] # on devrait trouver c = 1
c == 1 # mais Python nous répond que ce n'est pas le cas. 

False

**attention :** Pour effectuer des opérations sur un tableau `array`, il faut préciser que les éléments sont de type flottant. Observer par exemple le code suivant. 

In [17]:
a = np.array([2])
b = np.array([2], dtype='float')
a[0] /= 3
b[0] /= 3
print(a[0])
print(b[0])

0
0.6666666666666666


# Exercice 2 : Matrice d'adjacence, distances et triangles.

Pour rappel, un graphe est un couple $G = (S, A)$ constitué d'un ensemble $S$ (les sommets), non vide et fini, et d'un ensemble $A$ de paires d'éléments de $X$ (les arêtes). 
Un graphe est orienté si les arêtes ont une direction, c'est-à-dire si les couples d'éléments de $A$ sont des listes ordonnées, c'est-à-dire telle que pour deux sommets $i$ et $j$, $(i,j)$ n'est pas équivalent à $(j,i)$. Ici seuls des graphes non-orientés, c'est-à-dire dont les paires d'éléments de $S$ sont des ensembles non ordonnés ($\{i,j\} \in A$) sont considérés.

Par exemple, le graphe complet à $n$ sommets $K_n$ est le graphe de sommets $S = {0,1,2,\dots,n-1}$ ayant comme arêtes les parties à deux éléments de $S$. En particulier, $K_4 = (S,A)$ où $S=\{0,1,2,3\}$ et $A = \big\{ \{0,1\}, \{0,2\}, \{0,3\}, \{1, 2\}, \{1, 3\}, \{2, 3\}  \big\}$.

Dans ce TP, nous allons donc représenter un graphe par un couple de listes. Pour un graphe à $n$ sommets, les sommets seront représentés par des entiers allant de $0$ à $n-1$. 

Par exemple le graphe $G_1=(\{0,1,2,3\}, \{\{0,1\}, \{1,2\}, \{2,3\}, \{3, 1\}\})$ suivant est donné par

![G1](G1.png)

In [7]:
G1=([0,1,2,3],
          [(0,1),(1,2),(2,3),(3,1)])

On définit les trois graphes suivants : 

![G2](G2.png)

In [8]:
G2 = (list(range(18)),
      [(0,1),(1,2),(1,3),(2,3),(3,4),(3,10),(3,11),(3,12),(4,8),(4,7),(5,7),(6,7),(7,8),(7,9),(7,13),(7,12),(9,13),(10,11),(11,12),(11,16),(11,17),(12,15),(13,14),(13,15),(14,15),(16,17)
                  ])
G3 = ([i for i in range(13)],
     [(0,2),(1,2),(2,3),(3,4),(4,5),(4,10),(5,6),(5,7),(5,8),(5,9),(10,11),(10,12)])
G4 = (list(range(11)), 
     [(0,2),(1,3),(2,3),(2,4),(2,8),(3,4),(3,5),(4,5),(4,7),(4,8),(5,6),(5,7),(7,8),(7,10),(8,9)])

**a)** définir les graphes `G5` et `G6` suivants : 

![G56](G56.png)

A chaque graphe $G=(S,A)$ correspond une unique matrice  $A_G$ <!-- $=(a_{ij})_{1\le i,j\le n}$ --> 
symétrique de taille $n \times n$ avec $n=|S|$ donc le coefficient situé à la $i$-ème ligne et la $j$-ème colonne est $1$ si le $i$-ème sommet et le $j$-ème sommet sont adjacents, et $0$ sinon. Cette matrice est appelée la matrice d'adjacence de $G$. Par exemple, la matrice d'adjacence de $G_1$ est 
\begin{pmatrix}
0 & 1 & 0 & 0\\
1 & 0 & 1 & 1\\
0 & 1 & 0 & 1\\
0 & 1 & 1 & 0\\
\end{pmatrix}

**b)** Définir une fonction `A_complet` qui prend en paramètre un entier $n$ et renvoie la matrice d'adjacence du graphe complet à $n$ sommets. 

**c)** Définir une fonction `adjacence` qui étant donné un graphe, renvoie sa matrice d'adjacence. 

**d)** Ecrire les fonctions `nb_sommets` et `nb_aretes`, qui prennent en entrée la matrice d'adjacence d'un graphe et renvoient respectivemement le nombre de sommets et d'arêtes du graphe.

Dans un graphe $G=(S,A)$, étant donnés deux sommets $u,v\in S$, une marche de $u$ à $v$ est une suite de sommets $u_0, u_1, \dots, u_k$ telle que $u=u_0$, $u_k=v$ et pour tout $i=0,\dots, k-1$ les sommets $u_i$ et $u_{i+1}$ sont adjacents. On appelle $k$ la longueur de la marche. La distance de $u$ à $v$ correspond au plus petit entier $k$ tel qu'il existe une marche de $u$ à $v$ de longueur $k$. 

On peut démontrer que pour tout entier $k\ge 0$, la puissance $k$-ème de $A_G$ est symétrique et le coefficient associé au couple de sommets $(u,v)$ est égal au nombre de marches de longueur $k$ de $u$ à $v$. 



**e)** Ecrire une fonction `connexe` qui prend en entrée la matrice d'adjacence $A$ d'un certain graphe $G$ et qui détermine si $G$ est connexe ou non. 

indication : remarquer qu'il existe toujours une "courte" marche entre deux sommets d'une même composante connexe.

**f)** Ecrire une fonction `distance(A,u,v)` qui prend en entrée une matrice $A$ d'un certain graphe connexe $G$, deux sommets $u,v$ et qui renvoie la distance entre $u$ et $v$ dans le graphe $G$. 

Dans un graphe, on appelle triangle une clique avec 3 sommets, c'est-à-dire un ensemble de trois sommets deux à deux adjacents. 

**f)** En utilisant la fonction `trace`, écrire une fonction `nb_triangles` qui prend en entrée la matrice d'adjacence $A$ d'un certain graphe $G$ et qui détermine le nombre de triangles de $G$. On pourra vérifier son code sur un des exemples de graphes définis plus haut. 

indication : qu'est-ce qu'une marche de longueur $3$ d'un sommet vers lui-même ?

# Exercice 3 : Matrice d'incidence et cycles.

Dans cet exercice on s'intéresse à une autre représentation matricielle d'un graphe $G=(S,A)$ par ce qu'on appelle la matrice d'incidence, notée ici $I_G$. Cette matrice est de dimensions $n\times m$ où $n$ est le nombre de sommets et $m$ est le nombre d'arêtes. Chaque coefficient de cette matrice correspond donc à un certain couple $(u,a)\in S\times A$ et vaut $1$ si le sommet $u$ est une des deux extreminités de l'arête $a$, et $0$ sinon. L'ordre des colonnes (c'est-à-dire des arêtes) importe peu et est fixé de manière arbitraire. Par exemple, la matrice d'incidence du graphe $G_1$ est

\begin{pmatrix}
1 & 0 & 0 & 0 \\
1 & 1 & 0 & 1 \\
0 & 1 & 1 & 0 \\
0 & 0 & 1 & 1 \\
\end{pmatrix}

Attention : la matrice d'incidence n'est a priori pas une matrice carrée. 

**a)** Ecrire une fonction `incidence` qui prend en paramètre un graphe et renvoie sa matrice d'incidence. 

**b)** Ecrire une fonction `inc_to_graph` qui prend en entrée une matrice d'incidence et renvoie le graphe correspondant. On pourra par exemple représenter les sommets par des entiers de $0$ à $n-1$ où $n$ est le nombre de sommets du graphe. 

**c)** En utilisant la fonction `rang`, calculer le rang des matrices d'incidence des graphes $(G_i)_{i=1}^6$. Que remarquez-vous ? Que peut-on conjecturer ? Tester votre conjecture sur d'autres exemples de graphes de votre choix.  


**d)** Pour un graphe orienté, on définit sa matrice d'incidence en mettant pour l'arc $a=(u,v)$ un $1$ pour la case correspondante à $(e,v)$ et un $-1$ pour la case correspondante à $(e,u)$. En produisant des exemples de graphes orientés, essayer de caractériser structurellement le rang d'une matrice d'incidence d'un graphe orienté. 